version: 2
updates:
  - package-ecosystem: maven
    directory: "/java"
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/London
    ignore:
      - dependency-name: "com.amido.stacks.*"
        versions:
          - "*-PR"
    open-pull-requests-limit: 50
    rebase-strategy: disabled
