version: 2
updates:
  - package-ecosystem: maven
    directory: "/java"
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/London
    ignore:
      - dependency-name: "com.ensono.stacks.*"
        versions: ["*-PR"]
    open-pull-requests-limit: 10
    rebase-strategy: disabled
